name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12']

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      - name: Install dependencies
        run: |
          uv sync --dev

      - name: Run linting
        run: |
          uv run ruff check testzeus_mcp_server/

      - name: Run formatting check
        run: |
          uv run ruff format --check testzeus_mcp_server/

      - name: Run tests
        env:
          TESTZEUS_EMAIL: ${{ secrets.TESTZEUS_EMAIL }}
          TESTZEUS_PASSWORD: ${{ secrets.TESTZEUS_PASSWORD }}
          TESTZEUS_BASE_URL: ${{ secrets.TESTZEUS_BASE_URL }}
        run: |
          uv run pytest -v 2>/dev/null || echo "No tests to run"

      - name: Check build
        run: |
          uv build 