name: Build and Publish to PyPI

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      - name: Install dependencies
        run: |
          uv sync --dev

      - name: Run linting
        run: |
          uv run ruff check testzeus_mcp_server/

      - name: Run tests
        env:
          TESTZEUS_EMAIL: ${{ secrets.TESTZEUS_EMAIL }}
          TESTZEUS_PASSWORD: ${{ secrets.TESTZEUS_PASSWORD }}
          TESTZEUS_BASE_URL: ${{ secrets.TESTZEUS_BASE_URL }}
        run: |
          uv run pytest 2>/dev/null || echo "No tests to run"

      - name: Build package
        run: |
          uv build

      - name: Publish to PyPI
        env:
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          uv publish --token $PYPI_API_TOKEN 